### ISSUE TITLE
Embedding generation from MLMs/MLLMs 

### ISSUE THREAD

**Issue by nikhilbyte** [ritabratamaiti/AnyModal#3]
Hey thanks a lot for your work, it is very useful! 
I wanted to know how hard will it be to extract multimodal embeddings  from a fine tuned Multimodal LLMs like Llava, etc.

**Comment by ritabratamaiti** [comment]
Sounds interesting but I haven't yet looked into extracting multimodal embeddings. I have found this paper which may be what you are looking for: https://arxiv.org/abs/2407.12580
